### ISSUE TITLE
查询时报错

### ISSUE THREAD

**Issue by MCQTSS** [Womsxd/YuanShen_User_Info#38]
查询时报错提示
Traceback (most recent call last):
  File "xxx\ys_test.py", line 278, in <module>
    print(infoQuery('xxx'))
  File "xxx\ys_test.py", line 263, in infoQuery
    UidInfo = dataAnalysis(uid)
  File "xxx\ys_test.py", line 114, in dataAnalysis
    data = req.get_user_info(userid)
  File "xxx\main.py", line 174, in get_user_info
    return self._get_user_info(uid, GetInfo, GenshinUserData)
  File "xxx\main.py", line 166, in _get_user_info
    return func_ret(**getdata["data"])
  File "pydantic\main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GenshinUserData
stats -> win_rate
  field required (type=value_error.missing)
问题出在_get_user_info里return func_ret(**getdata["data"])这一行
不知道怎么修复希望看到能更新一下或者指点一下怎么修复这个问题

**Comment by abbhb** [comment]
structs.py里删除win_rate就正常拿到数据了，不知道为什么

**Comment by MCQTSS** [comment]
> structs.py 里删除win_rate就正常拿到数据了，不知道为什么

谢谢大佬，已经解决了
